# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

variables:
  COMMIT_ID: e1e81264dc1d6362c9c3ee3b7752ad9e035c4a09
  ENDPOINT: build

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

extends:
  ${{ if eq(variables.ENDPOINT, 'build') }}:
    template: resources-template.yml
  ${{ if eq(variables.ENDPOINT, '') }}:
    template: resources-template.yml
