# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

parameters:
- name: "platforms"
  type: object
  default:
  - vs
  - broadcom

stages:
- stage: Build
  condition: false
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - template: multi-jobs-template.yml
    parameters:
      jobs:
      - job: Test
        steps:
        - script: |
            sudo pip install pytest==4.6.2 attrs==19.1.0 exabgp==4.0.10 distro==1.5.0 docker==4.4.1 redis==3.3.4 flaky==3.7.0
            which pytest
            cat $(which pytest)
  - job: Test
    steps:
    - script: |
        sudo pip install pytest==4.6.2 attrs==19.1.0 exabgp==4.0.10 distro==1.5.0 docker==4.4.1 redis==3.3.4 flaky==3.7.0
        which pytest
        cat $(which pytest)
