# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

parameters:
- name: "platforms"
  type: object
  default:
  - vs
  - broadcom

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - none

stages:
- stage: Build
  condition: ${{ containsValue(parameters.platforms, 'vs1') }}
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: Build
    timeoutInMinutes: 60
    steps:
    - script: |
        echo "Build"
      displayName: Build script
